# Generated by Django 4.0.6 on 2022-11-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='attendees',
            new_name='attendee',
        ),
        migrations.AddField(
            model_name='owners',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='performer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='venue_manager_app.performers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venues',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
